name: Protection check
on: pull_request_target

jobs:
  forkedpr-check:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Copy code
        uses: actions/checkout@v4

      - name: check workflows and tests changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            tests:
              - 'tests/**'
            workflows:
              - '.github/workflows/**'

      - name: Throw tests warning 
        if: steps.changes.outputs.tests == 'true'
        run: echo "::warning ::There are some changes in Sinergym tests."

      - name: Throw workflows exception
        if: steps.changes.outputs.workflows == 'true'
        run: |
          echo "Forked repositories have no permission to modify workflows. Please, contact with Sinergym administrator."
          exit 1

