ignore:
  - "sinergym/utils/gcloud.py"
  - "sinergym/utils/evaluation.py"
  - "sinergym/utils/env_checker.py"
  - "sinergym/utils/callbacks.py"
  - "sinergym/simulators/base.py"
  - "sinergym/simulators/eplus_alpha.py"

coverage:
  status:
    project: false
